/**:
  ros__parameters:
    camera:
      model: Pinhole
      width: 640
      height: 480
      scale: 1.0
      # our g1
      # fx: 606.9859619140625
      # fy: 607.0111083984375
      # cx: 311.51885986328125
      # cy: 247.2598419189453
      # d0: -0.00
      # d1: 0.00
      # d2: -0.00
      # d3: 0.000

      # # D-robotics G1
      # fx: 385.3792724609375
      # fy: 385.3792724609375
      # cx: 320.58416748046875
      # cy: 240.083740234375
      # d0: -0.057185977697372437
      # d1: 0.0680452287197113
      # d2: -9.277134813601151e-05
      # d3: 0.0007549661095254123
      # d4: -0.022183749824762344
      # demo
      fx: 607.293212890625
      fy: 607.1084594726562
      cx: 329.4767761230469
      cy: 250.3979797363281
      d0: -0.00
      d1: 0.00
      d2: -0.00
      d3: 0.000