main:
  device: cuda
  use_gpt: false
  dataset: horizon #scannet # hm3dsem #replica #iphone
  scene_id: icra_ic3f
  dataset_path: /mnt/holoagent/fsrvln/rgbd_datasets/
  depth_cut: 6.0
  save_path:  /mnt/holoagent/fsrvln/scene_graphs_opensource
models:
  clip:
    type: ViT-L/14 # ViT-B-32 # ViT-H-14 
    checkpoint: checkpoints/open_clip_pytorch_model.bin
  sam:
    checkpoint: checkpoints/sam_vit_h_4b8939.pth
    type: vit_h
    points_per_side: 12
    pred_iou_thresh: 0.88
    points_per_batch: 144
    crop_n_layers: 0
    stability_score_thresh: 0.95
    min_mask_region_area: 100
pipeline:
  voxel_size: 0.05
  skip_frames: 15
  init_overlap_thresh: 0.75
  overlap_thresh_factor: 0.025
  iou_thresh: 0.05
  clip_masked_weight: 0.4418
  clip_bbox_margin: 50 # in pixels
  feature_dbscan_eps: 0.01
  max_mask_distance: 10000 # 6.4239 in meters
  min_pcd_points: 100
  depth_weighting: false
  grid_resolution: 0.05
  merge_type: sequential # hierarchical
  save_intermediate_results: true
  obj_labels: SCANNET200 #FINALLABEL #SCANNET20 #COCO_STUFF_CLASSES #IMAGENET21K_LABELS #HM3DSEM_LABELS
  merge_objects_graph: false  
